name: example
description:
  Example showing how to use QuoteBuffer.

homepage: https://github.com/simphotonics/quote_buffer

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  quote_buffer:
    path: ../
  code_builder: ^3.2.1
  dart_style: ^1.3.3
  ansicolor: ^1.0.2
