name: quote_buffer

description: Extension methods for transforming objects and iterables into
  quoted strings and writing them to a string buffer.

version: 0.2.8

homepage: https://github.com/simphotonics/quote_buffer

environment:
  sdk: '^3.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
