name: quote_buffer

description: Extension methods on StringBuffer for
  transforming objects and iterables into quoted strings.

version: 1.0.0

homepage: https://github.com/simphotonics/quote_buffer

environment:
  sdk: '^3.13.0'

dev_dependencies:
  lints: ^6.1.0
  test: ^1.32.0
